name: Build and Deploy to Azure

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # 1. Login to your ACR
      - name: Log in to Azure Container Registry
        uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.AZURE_REGISTRY_SERVER }}
          username: ${{ secrets.AZURE_REGISTRY_USERNAME }}
          password: ${{ secrets.AZURE_REGISTRY_PASSWORD }}

      # 2. Build and Push using the unique GitHub SHA to avoid tag conflicts
      - name: Build and push container image
        run: |
          docker build -t ${{ secrets.AZURE_REGISTRY_SERVER }}/resepin-laravel:${{ github.sha }} .
          docker push ${{ secrets.AZURE_REGISTRY_SERVER }}/resepin-laravel:${{ github.sha }}

      # 3. Deploy directly using the Publish Profile
      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ secrets.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          images: '${{ secrets.AZURE_REGISTRY_SERVER }}/resepin-laravel:${{ github.sha }}'